tap 'homebrew/versions'

brew 'awscli'
brew 'android-sdk'
brew 'ansible'
brew 'autoconf'
brew 'automake'
brew 'boost'
brew 'boot2docker'
brew 'cabal-install'
brew 'docker'
brew 'emacs', args: ['cocoa']
brew 'freetype'
brew 'gdbm'
brew 'gettext'
brew 'ghc'
brew 'git'
brew 'glib'
brew 'gradle'
brew 'graphviz'
brew 'imagemagick'
brew 'jpeg'
brew 'libevent'
brew 'libffi'
brew 'libpng'
brew 'libtool'
brew 'libyaml'
brew 'markdown'
brew 'mongodb'
brew 'mysql'
brew 'nvm'
brew 'openssl'
brew 'pandoc'
brew 'pcre'
brew 'pkg-config'
brew 'plantuml'
brew 'rbenv'
brew 'rbenv-gem-rehash'
brew 'rbenv-gemset'
brew 'readline'
brew 'redis'
brew 'ruby-build'
brew 'source-highlight'
brew 'tree'
brew 'terminal-notifier'
brew 'wget'
brew 'zsh'
brew 'zsh-syntax-highlighting'

tap 'homebrew/binary'
brew 'packer'


# brewcask
tap 'phinze/homebrew-cask'
brew 'brew-cask'

cask 'atom'
cask 'basictex'
cask 'blender'
cask 'dropbox'
cask 'evernote'
cask 'flash'
cask 'gimp'
cask 'google-chrome'
cask 'google-japanese-ime'
cask 'gyazo'
cask 'heroku-toolbelt'
cask 'inkscape'
cask 'iterm2'
cask 'java'
cask 'keyremap4macbook'
cask 'onepassword'
cask 'sequel-pro'
cask 'sketch'
cask 'skitch'
cask 'skype'
cask 'slack'
cask 'unity3d'
cask 'vagrant'
# cask 'virtualbox'

# R
brew 'gcc'
cask 'xquartz'
tap 'homebrew/science'
brew 'R'
cask 'rstudio'
