tap "caskroom/cask"
brew "readline"
brew "sqlite"
brew "ansible"
brew "autoconf"
brew "automake"
brew "byobu"
brew "gettext"
brew "glib"
brew "git"
brew "carthage"
brew "cmake"
brew "cocoapods"
# brew "coreutils"
# brew "gcc"
brew "ios-deploy"
brew "ideviceinstaller"
brew "libimobiledevice", args: ['HEAD']
brew "libtool"
brew "graphviz"
brew "hugo"
brew "imagemagick"
brew "jq"
brew "mysql", restart_service: true
brew "nkf"
brew "pandoc"
brew "plantuml"
brew "ruby-build"
brew "source-highlight"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"
brew "yarn"
brew "zsh"
brew "zsh-syntax-highlighting"
cask "android-sdk"
cask "android-ndk"
cask "android-studio"
cask "android-platform-tools"
cask "docker"
cask "emacs"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-japanese-ime"
cask "java"
